// Generated by scripts/pick-ui-seeds.sh (#404) from a headless probe: don't edit by hand, rerun the script.

/// The seeds the UI tests launch, each the first in 1...400 meeting its test's condition.
enum SeedTable {
    /// `ResultsUITests.testSheetAppearsAbout3sAfterFinishWhileSceneRenders`: the `-demo -laps 1` race on which your
    /// boat finishes at least 1680 ticks (14 s at `-timescale 4`) before the close. Probed: she finishes at tick
    /// 6171, the race closes at 9195.
    static let resultsSheet: UInt64 = 6
}
