import Foundation

/// One third-party component's licence, for Settings → About → Acknowledgements (#25).
///
/// `Acknowledgements.plist` is generated by `scripts/generate-acknowledgements.swift` from the resolved Swift
/// packages and `ThirdParty/`; CI fails if it's out of date.
struct Acknowledgement: Decodable, Equatable {
    var name: String
    var version: String?
    var license: String

    /// The list bundled with the app, sorted by name.
    static func bundled(in bundle: Bundle = .main) throws -> [Acknowledgement] {
        guard let url = bundle.url(forResource: "Acknowledgements", withExtension: "plist") else {
            throw CocoaError(.fileNoSuchFile)
        }
        return try PropertyListDecoder().decode([Acknowledgement].self, from: Data(contentsOf: url))
    }
}
