#!/usr/bin/env bash
# Regenerates the UI tests' seed table, RegattaUITests/SeedTable.swift (#404): each seed a UI test launches is the
# first one a headless probe finds meeting the test's condition, never a hand pick. A UI test can't sail a headless
# race at test time, so a sim or bot change that moves the outcome is one run of this script, then CI.
#
#   scripts/pick-ui-seeds.sh           probe and rewrite the table
#   scripts/pick-ui-seeds.sh --check   probe and report where the table differs, without rewriting (exit 1 if it does)
#
# The probe is `regatta-botsuite results-seed` (Packages/RegattaCore, release build, through scripts/heavy.sh).
# Rows (only one today):
#   resultsSheet  ResultsUITests.testSheetAppearsAbout3sAfterFinishWhileSceneRenders: `-demo -laps 1 -timescale 8`
#                 (7 opponents, the launch race), your boat finishes >= 14 s of wall-clock time before the close:
#                 -timescale 8 runs at most 240 ticks/s, so >= 3,360 ticks.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root"

check=false
case "${1:-}" in
    "") ;;
    --check) check=true ;;
    -h | --help) sed -n '2,13p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "usage: scripts/pick-ui-seeds.sh [--check]" >&2; exit 2 ;;
esac

package=Packages/RegattaCore
scratch=.build/check/RegattaCore
probe="$scratch/release/regatta-botsuite"
build_log="$(mktemp)"
trap 'rm -f "$build_log"' EXIT
# A failed build stops here: never probe with whatever binary an earlier build left.
if ! scripts/heavy.sh swift build -c release --package-path "$package" --scratch-path "$scratch" \
    --product regatta-botsuite >"$build_log" 2>&1; then
    grep -E "error" "$build_log" >&2 || tail -20 "$build_log" >&2
    echo "pick-ui-seeds.sh: building the probe failed" >&2
    exit 1
fi
grep -E "warning: unre" "$build_log" || true
[[ -x "$probe" ]] || { echo "pick-ui-seeds.sh: no probe at $probe" >&2; exit 1; }

found="$("$probe" results-seed --from 1 --to 400 --laps 1 --opponents 7 --min-gap-ticks 3360)"
echo "resultsSheet: $found"
read -r _ seed _ finish _ close <<<"$found"

table=RegattaUITests/SeedTable.swift
generated="$(mktemp)"
trap 'rm -f "$build_log" "$generated"' EXIT
cat >"$generated" <<SWIFT
// Generated by scripts/pick-ui-seeds.sh (#404) from a headless probe: don't edit by hand, rerun the script.

/// The seeds the UI tests launch, each the first in 1...400 meeting its test's condition.
enum SeedTable {
    /// \`ResultsUITests.testSheetAppearsAbout3sAfterFinishWhileSceneRenders\`: the \`-demo -laps 1\` race on which your
    /// boat finishes at least 3,360 ticks (14 s at \`-timescale 8\`) before the close. Probed: she finishes at tick
    /// $finish, the race closes at $close.
    static let resultsSheet: UInt64 = $seed
}
SWIFT

if cmp -s "$generated" "$table"; then
    echo "$table is up to date"
elif $check; then
    echo "pick-ui-seeds.sh: $table differs from the probe:" >&2
    diff -u "$table" "$generated" >&2 || true
    exit 1
else
    cp "$generated" "$table"
    echo "rewrote $table"
fi
